language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7.0
  
install:
 - composer --prefer-dist install

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

script:
  - ./vendor/bin/phpcs --standard=PSR2 --report=emacs --extensions=php --warning-severity=0 src/
